# Generated by Django 4.1.13 on 2024-05-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_surveys_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Surveys',
        ),
    ]
