# Generated by Django 4.1.13 on 2024-05-10 01:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchased_course',
            old_name='status',
            new_name='completed',
        ),
        migrations.AddField(
            model_name='courses',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 5, 9, 21, 21, 20, 270758)),
        ),
        migrations.AddField(
            model_name='courses',
            name='recipe',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='purchased_course',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchased_course',
            name='purchased_at',
            field=models.DateField(default=datetime.datetime(2024, 5, 9, 21, 21, 20, 271759)),
        ),
        migrations.AlterField(
            model_name='courses',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courses_media',
            name='url_cover',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='courses_media',
            name='url_video',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='purchased_course',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
