# Generated by Django 4.1.13 on 2024-05-14 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_status_purchased_course_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 5, 14, 13, 1, 45, 394638)),
        ),
        migrations.AlterField(
            model_name='purchased_course',
            name='purchased_at',
            field=models.DateField(default=datetime.datetime(2024, 5, 14, 13, 1, 45, 395636)),
        ),
    ]
