# Generated by Django 4.1.13 on 2024-05-30 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courses_category_alter_courses_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='purchased_course',
            name='purchased_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
