# Generated by Django 4.1.13 on 2024-05-16 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courses_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 5, 16, 1, 24, 55, 307679)),
        ),
        migrations.AlterField(
            model_name='purchased_course',
            name='purchased_at',
            field=models.DateField(default=datetime.datetime(2024, 5, 16, 1, 24, 55, 308681)),
        ),
    ]
