# Generated by Django 4.1.13 on 2024-05-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_courses_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased_course',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
