# Generated by Django 4.1.13 on 2024-05-20 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courses_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 5, 20, 19, 18, 22, 941263, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='purchased_course',
            name='purchased_at',
            field=models.DateField(default=datetime.datetime(2024, 5, 20, 19, 18, 22, 941263, tzinfo=datetime.timezone.utc)),
        ),
    ]
