# Generated by Django 4.1.13 on 2024-05-22 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_courses_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='courses_media',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='purchased_course',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='purchased_course',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='courses',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchased_course',
            name='purchased_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
