# Generated by Django 4.1.13 on 2024-05-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_category_id_courses_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
