# Generated by Django 4.1.13 on 2024-05-10 01:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient_recipes',
            old_name='Ingredient_id',
            new_name='ingredient_id',
        ),
        migrations.RenameField(
            model_name='ingredient_recipes',
            old_name='Ingredient_quantity',
            new_name='ingredient_quantity',
        ),
        migrations.AddField(
            model_name='recipes',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 5, 9, 21, 22, 16, 365971)),
        ),
    ]
