# Generated by Django 4.1.13 on 2024-05-20 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipes_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient_recipes',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
    ]
