# Generated by Django 4.1.13 on 2024-05-14 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveys',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 5, 14, 13, 1, 45, 401637)),
        ),
    ]
