# Generated by Django 4.1.13 on 2024-05-14 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_rename_ingredient_id_ingredient_recipes_ingredient_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 5, 14, 13, 1, 45, 397636)),
        ),
    ]
