# Generated by Django 4.1.13 on 2024-05-16 05:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipes_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2024, 5, 16, 1, 24, 55, 310678)),
        ),
    ]
